// import { Inter } from "next/font/google";
import "./globals.css";
import Rodape from "@/componentes/rodape";
import Header from "@/componentes/cabecalho";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <Header/>
        <div className="layout">
        {children}
        <Rodape/>
        </div>
        </body>
    </html>
  );
}
